### ISSUE TITLE
Text box traps all keystrokes when returning focus to Thunderbird

### ISSUE THREAD

**Issue by Izwbusr** [opto/nostalgy-xpi#169]
Hi,

Using 91.6.2 (64-bit), Windows 10, Nostalgy 3.2.17.

I have the following issue:

1. Key is pressed to save a message but save is not completed.
2. Focus changes to another application.
3. Focus returns to Thunderbird.
4. Click on another message with mouse.
5. All keys are treated as if they are typing in the white character box at the bottom, including Backspace (word "Backspace" is entered in the white box), Tab, Escape, etc.

What is expected is that when another message is selected (step 4), or when focus returns (step 3), the text box at the bottom closes.  To close the text box (and fix the problem), I have to click on the window's bottom gray bar.  Then things return to normal.

Hope this helps.

**Comment by opto** [comment]
Please put cursor in box and press escape.That closes the box. It does 
not help to press escape if the focus is not inside the box.

**Comment by Izwbusr** [comment]
If I click anywhere in the bottom bar (including the text box), the text box closes.  But, if I have to go to my mouse and reestablish focus on the text box, then it defeats the purpose of using keyboard to quickly manage emails.  Version 3.0.11 had the correct behavior.

**Comment by opto** [comment]
you only have to reestablish focus if you loose it by some user action. 
I think you mentioned switching tabs.

If you start and finish an action, I think it does not loose focus, at 
least not on win 11 64bit

you mentioned:

 1. Key is pressed to save a message but save is not completed.
 2. Focus changes to another application.


The correct workflow is to close by esc before changing focus.

**Comment by Izwbusr** [comment]
Thanks for the reply.

If focus is lost due to user selecting another window, opening a message, etc. and returns, then one of two things happen:

1. If the action was not finished, then the text box "traps" all keystrokes.  If you press Esc, the word "Escape" is shown in the text box.  If you select another message and press Tab, the word "Tab" is shown in the text box.  If you press S, then "S" is shown in the text box.  There is no way to exit this "trap".  To exit you need to select another tab and return to the original tab.
2. If the action as finished then keys do not work.  You need to select another tab and return and then keys work again.

In my view, version 3.0.11 worked correctly.

Thanks,

**Comment by opto** [comment]
You are right, you need to end the unwanted action by esc before 
switching focus.

Like: S ... oh, I didn't want this ... press esc ... Message ID: 
***@***.***>

If we want the history etc. in the box to work, then the box is as it 
is, it is programmed by TB, not by Nostalgy. We are just using it. The 
reduced features of the old version work as well, but we can't have both 
in one version, as far as I know.

**Comment by Izwbusr** [comment]
It can't be intentional that if you forget to press Esc before changing focus, then you are trapped in a text box.  If I press Esc after landing in this trap, then the normal effect of Esc (i.e. escaping) no longer works.  The word "Escape" is written into the text box with no actual escaping action taking place.  Every keystroke is typed into that textbox, even if you click on other messages, folders, etc.  In other words, Thunderbird no longer responds to any keystroke (is semi-functional) until you perform some hidden combination of actions with a mouse.  To actually escape, you need to cycle through tabs with the mouse.  This is can't possibly be by design.

**Comment by opto** [comment]
yes, when the old xul:textbox was replaced by html:input, at that time, 
this functionality came up: The word "Escape" is written into the text 
box with no actual escaping action taking place

xul:textbox was closed by esc, input is not.That is one of the wonders 
of making TB a web application, which is underway since TB 60.

**Comment by opto** [comment]
it is just another point in time when you have to press esc: now, you 
have to do it before changing focus. It is no more key presses than before.

**Comment by Izwbusr** [comment]
You are explaining why this behavior happens and not why it is elegant design.  In my opinion, as I have said, it is not intuitive or useful.  For my purposes (i.e. being able to quickly handle email with keyboard), the current behavior makes it unusable.  I guess all I can do at this point is continue to use version 3.0.11 and hope a future version changes the "design".

**Comment by opto** [comment]
>why it is elegant design

it is designed by TB, so this is the wrong place to ask.


 >the current behavior makes it unusable

I easily remembered to press esc before(!)  refocus (which works 
perfectly if done before refocus), but is obviously is a personal choice 
which version to use.

**Comment by opto** [comment]
maybe what I do not understand is why don't you close the box by esc, if 
you don't need it? Meaning close it before going elsewhere?

**Comment by Izwbusr** [comment]
Thank you for your time in following up.

If I am scrolling down emails and filing them, copying them, etc. I may come across one that I think goes in a specific folder, so I start typing the name of the folder.  I may then want to make sure it is the email I thought it was and open to read it.  Then one of two things happen:

1. If I forgot to press Esc before opening, I am now stuck in the text box trap.  When trying to process lots of emails quickly, it is very easy to forget to press Esc before opening an email or changing focus to another App.  If you do, you are trapped.

2. If I did remember to press Esc,  upon returning focus to email list, the keys no longer work and I have to click another tab and return to "reset" keys functionality.

Either way, it is very cumbersome to continue to process emails quickly if focus is interrupted even if to read the email you are trying to file.

Thanks

**Comment by opto** [comment]
in the new version, you can file directly from a message window. I 
reenabled that in one of the last versions.

**Comment by opto** [comment]
I think this is solved

**Comment by Izwbusr** [comment]
I can confirm that for TB 91.9.1 (32-bit) with Nostalgy ++ 3.4.2, this is NOT fixed.
