### ISSUE TITLE
Cursor stay in recipient adress field when replying

### ISSUE THREAD

**Issue by oliv316** [opto/nostalgy-xpi#287]
Hi
When I reply to a email, cursor stay in recipient Field , instead goes in the mail body
I must use Tab or my mouse to move it in the body 
Tanks

**Comment by opto** [comment]
esc-esc also moves to body.

https://github.com/opto/nostalgy-xpi/releases/tag/v4.5.32 may (??) solve this.
In general, it uses: a) we have subject b) we have recipients
to move to body.

This version has a little delay before the discovery of a) and b) is done. Maybe it helps

Klaus

**Comment by oliv316** [comment]
Yes ! great ! thanks a lot for your work !

**Comment by oliv316** [comment]
I hoped  the problem was fixed but not, because I forgot to activate the plugin

I have the same issue with V4.5.32 and V 4.5.33  whith thunderbird 128.
I need to use Tab key twice to move  cursor to the body 

When I reply to a email, cursor blink in body during a very short time (milisecond) and return to recipient field

esc-esc does not work

Thanks

**Comment by polychronakis** [comment]
Same for me. I just tested v4.5.33 with TB v128.8.0esr (Windows 11) and the problem persists. Once the reply window pops up, the cursor is initially focused in the "To" field, and after ~0.5sec jumps to the main body.

In case it helps: I noticed that after TB is restarted, the first time I reply to a message, I the jumping delay is a bit lower (say ~0.2sec). In any subsequent reply, they delay is longer.

Esc-esc also doesn't work for me.

The only other extension I have is tbkeys. I disabled it and left only Nostalgy enabled, but the same thing happens.

Since this is a reply to an existing message, why is discovery of (a) and (b) needed in the first place? We are replying to a previous message, so it's safe to assume that there are recipients and subject. Can this check be skipped altogether and always focus the cursor in the main body without any delay when replying to a previous message?

Thank you so much for looking into this!

**Comment by jmechler** [comment]
This delay is actually worse than having the cursor stay on the to: field. 

If you start typing your reply quickly, you get a few characters in and then TB auto-completed. you can't even really tell it happened.  See issue #289

**Comment by sebadrude** [comment]
exactly, @jmechler, it often remains unnoticed and therefore has the potential to cause much harm, sending mails to people that should not get them.

**Comment by dbergol** [comment]
Any news on this? I have no problem with it in TB 128 ESR but in recent TB releases

**Comment by fmicolletffcam** [comment]
> Any news on this? I have no problem with it in TB 128 ESR but in recent TB releases

+1 Is there any chance that it could be solved in the upcoming version for TB 141?
Does anyone has a hack other than 'tabtab' or the ugly `xdotool` workaround that I use in an Xorg desktop (I use Awesome on my work's machine)

**Comment by fmicolletffcam** [comment]
This one is not _yet_ solved in the 4.5.57 version. ;)

**Comment by sebadrude** [comment]
This is really unfortunate.  I detect the error about 10 times a day and manually delete the wrong recipient.  But once or twice a week, especially if I reply with a one-liner, the error slips though my attention, and I have to apologize to (often the same) people -- and that is least bad case scenario.
This bug (I consider this to be a bug) has been reported several times, if I remember correctly: over years, and yet does not get solved.
As somebody rightly observed: when one is replying to one or all recipients, it can be safely assumed that there is a subject and that there are recipients.  So why have the checking routine that sends the cursor to the recipient field in the first place?  And if that cannot be avoided, why not do it in the background, before making the window active for receiving input?
This is poor design, and it does and does and does not get resolved.

**Comment by oliv316** [comment]
It seems ok withs 4.5.57 and thunderbird 140.1.0esr
I hope this issue fixed
tanks for the job !

**Comment by polychronakis** [comment]
Unfortunately the issue still persists for me with 141.0 + 4.5.57

**Comment by sebadrude** [comment]
For me as well, TB 140.0.1 and v4.5.54, problem persists.

**Comment by opto** [comment]
there is a delay of 300ms before the Nostalgy code is injected into the compose window. Maybe that is the reason?

Reason for the delay is that the compose window was not fully drawn when already our code went into it, so our code failed.

Next week, I can test whether the delay is still needed or whether that was before 115, 128 or 140,

But this will also depend on PC speed and what other tasks are running.

Klaus

**Comment by sebadrude** [comment]
Thanks SO much for looking into this!
In earlier discussion, it was said that a check whether a recipient (To-field) and Subject are present is done, which is why the cursor is going there (and sometimes stays there, sometimes stays there only for a short while and then goes to the main text editor window).
If that is the case, a question would be whether this check is really needed when answering to another message.

**Comment by sebadrude** [comment]
Here is an example I just filmed: https://e.pcloud.link/publink/show?code=XZjeBEZJbgWDEouytStnN2DQaGHAkDagrRy
I press Ctrl+Shift+R and start to type "Oi Adrienne".
The O goes into the main window (apparently even while the window opens), but then the cursor goes quickly into the "To-Field", which receives the next two keystrokes (the "i" and a space), and then returns to the main window.  In this case, there is no address which starts with "i ", but in many cases it is only one letter which is inserted there, and then the first person whose name starts with this letter will be inserted into the To-field, and often I will not even have noticed that.
This is very dangerous, depending on who sits in my address book and must not receive certain messages...
And it does not happen when I disable Nostalgy++, however fast I may type.

**Comment by opto** [comment]
[manage_emails_nostalgy_pp_4.5.60-tb.zip](https://github.com/user-attachments/files/21538028/manage_emails_nostalgy_pp_4.5.60-tb.zip)

this version has a mini delay (if a delay is set to 0, it is not 0, but "somewhat longer")

Maybe you can try this. Please also when show cc or bcc is set in options.

I think you can load zip files, if not, then rename to xpi

Klaus

**Comment by polychronakis** [comment]
Thank you for looking into it! I really appreciate it. I just tested it but unfortunately the same behavior persist. The delay feels a bit shorter in this version, but the focus still goes to 'To' for a few ms before jumping to the main body, enough to mistakenly add an extra recipient.

**Comment by oliv316** [comment]
for me , version 4.5.57 was better than 4.5.60 , version 4.5.6 do not work correctly , version  4.5.57 did ! ,
But with 4.5.57, the first time i do a repply , cursor goes to the recipient fiedl, 
if I close the windows , and  do again  repply , it's ok , cursor goes directly in body field and It's ok for all next reply I do until I close and re-open Thunderbird. I had reinstalled V 4.5.57
I hope it will help you to find the right fix

**Comment by opto** [comment]
this was tricky.

this might work.  It may looses characters in the message body if TB is slow but should not go into to.

[manage_emails_nostalgy_pp_4.5.64-tb.zip](https://github.com/user-attachments/files/21554253/manage_emails_nostalgy_pp_4.5.64-tb.zip)

**Comment by opto** [comment]
tested in128

**Comment by polychronakis** [comment]
A big thank you! This works great for me (141.0 + 4.5.64)! The cursor goes straight to the main body and I can start typing instantly. A character may be lost, but only if I start typing super fast (I had to intentionally try to make it miss a character). Under normal typing, this delay is unnoticeable.

I really appreciate your effort to fix this issue!

**Comment by salzrat** [comment]
Also works great on 140.1 ESR! 
One question - I originally installed nostalgy from the Addon-page. If I now have installed this version from file, will the addon still get updated automatically when a new release hits the addons-page?

**Comment by sebadrude** [comment]
GREAT!!
This seems to work indeed!  I tested it a couple of times, and the cursor did not got to the "to"-field.

**Ganz, ganz herzlichen Dank** für diese Verbesserung!

**Comment by opto** [comment]
Thanks for your responses.

Did anybody test this for TB 128 or 115?

**Comment by salzrat** [comment]
I'm not sure this is related, but since I installed this fix, I cannot use "Ctrl-M" to start a new message. Only if I press Ctrl-M quickly a few times does the new message window appear. If I disable Nostalgy it works normally again. I didn't notice this before...

**Comment by opto** [comment]
if you uncheck ... use ctrl .. in the options, that should be ok

It seems that feature makes normal ctrl-letter combinations unusable

**Comment by sebadrude** [comment]
@salzrat :  True, I noticed the same with "Ctrl+R" and "Ctrl+Shift+R".
You mean, Klaus, we should not use "Ctrl+1", "Ctrl+2" etc. any more as shortcuts in Nostalgy++?
Does this hold also for Ctrl+Shift+1 etc?

Well, that sort of defeats whole the purpose of Nostalgy++, doesn't it? :-(

**Comment by salzrat** [comment]
I've never used these shortcuts. For me, filing into folders works perfectly - and unchecking the "Use Ctrl" option fixed the Message Pane problem.

**Comment by sebadrude** [comment]
Oh, then I probably misunderstood something.  Sorry.
I thought we should not choose "Ctrl+..." combinations as shortcuts in Nostalgy, which is most of what I use it for.
Could you please point me at where this "Use Ctrl" option is located?  In TB or in Nostalgy (which confituraion menu)?  I am not able to find it.

**Comment by opto** [comment]
in Nostalgy options, on the completion tab.

**Comment by opto** [comment]
or try this version:

[manage_emails_nostalgy_pp_4.5.59a-tb.zip](https://github.com/user-attachments/files/21566726/manage_emails_nostalgy_pp_4.5.59a-tb.zip)

**Comment by sebadrude** [comment]
Ah, found it.  "Use Ctrl instead of esc ..."  Thanks.

The (minor) problem persists, though: when on an e-mail with focus either in the email-list-panel or in the reading-panel, pressing Ctrl+R or Ctrl+Shift+R does not do anything, the first time.  Pressing it twice, it works as expected.  And from then on, pressing it once works as well, unless you set the focus on another e-mail.
But this is a minor problem indeed, I can live with that.

**Comment by opto** [comment]
@sebadrude : where do you use the ctrl+1 etc. shortcuts?On my machine, they open the tabs

**Comment by opto** [comment]
@sebadrude do you mean the 4.5.59a version? At least after a restart, if I press ctrl-m, it directly opens the new mail window (in Win 11)

**Comment by sebadrude** [comment]
I tested the 4.5.59a version now, and the problem with pressing Ctrl+R disappeared.  Chapeau!

> ctrl+1 etc. shortcuts, [...] on my machine, [...] open the tabs
True, I see this now, but this seems to be used to be overridden by Nostalgy++. 

Until recently:
> where do you use the ctrl+1 etc. shortcuts?
I follow an implementation of the "getting things done" philosophy in TB.  There, I process all mails in my inbox quickly, for instance, I use Ctrl+3 for moving a mail into a folder "3--TODAY", Ctrl+4 to move the mail into a folder "4--ASAP", Ctrl+5 to move the mail into a folder "5--Waiting-for", and so on.
This is why I rely so heavily on Nostalgy++.  

But indeed, now these keystrokes do not any more what I intended them to do, also not with Shift, which I use for mails in another account.  As I said, until recently, this worked fine, so it seems Nostalgy++ overwrote the default keyboard shortcuts, but doesn't do that any more.  Also not if I switch "Use ctrl instead of esc..." on again.

This breaks my workflow based on Nostalgy++ in TB... :-(

**Comment by sebadrude** [comment]
These keyboard-shortcuts in Nostalgy++ used to work for years until yesterday:
<img width="654" height="231" alt="Image" src="https://github.com/user-attachments/assets/8b92e786-3f09-493d-a9c2-329b6578c9bc" />

**Comment by sebadrude** [comment]
I tried to unset the default keyboard shortcuts in TB using https://github.com/wshanks/tbkeys, adding the lines 
    "ctrl+3": "unset",
    "ctrl+4": "unset",
    "ctrl+5": "unset",
    "ctrl+6": "unset",
etc. to the settings of that addon.
That did disable the default TB behavior (changing to Tab X) but did not free them to be re-set by Nostalgy++, I am afraid.

**Comment by opto** [comment]
yes, I have disabled the ctrl, in a next version, I can change that if use ctrl... is disabled.

that means you will ave the ctrl keys, but, as up to now, esc will not clear quick filter.

or you set to use ctrl, then esc clears the quickfilter, but you loose the individual settings for your ctrl combinations.

I will make a new version probably sometime tomorrow.

**Comment by opto** [comment]
you can also use the text insert addon to define shortcuts, but it needs a few more keystrokes.
E.g., if you want to move to the folder defined by 1:

s  then in the box:   1ctrl-d   (ctrl and d pressed simultaneusly)

**Comment by sebadrude** [comment]
Thanks again for continuing to work on these issues.  One fix causes another feature to break...  **sigh***

As to the "text insert addon", I tried that out as you promoted in on the page that appears when you installed Nostalgy++.

But that addon broke, for me (Currently Windows 11 Pro, TB 140.0.1 (64-bit), Nostalgy++ v4.5.54 as installed manually from your link; NO other addons installed so far in TB; I also use Linux Mint but have not tested anything there), the movements through the text -- left, right, up and down keys and their combination with Ctrl and Ctrl+Shift did not work any more.  Only "Home" and "End" and combinations using these did work, for any other movement I had to use the mouse.  So I uninstalled that addon immediately.  But that would be another issue related to another addon, which I did not yet bother to submit.

**Comment by opto** [comment]
thanks for reporting the issue with text insert! I will look at that as well. 
Not sure I tested that in 141. Contrary to the legacy addons, which break often, the webextention addons are supposed to work indefinitely, so we are not "allowed" to put a max TB version in there, which leads to assuming it works and to not testing ...

**Comment by opto** [comment]
...  I just verified that left, right, up and down keys work in my 128.

It is annoying how often the new TB versions break the addons.

**Comment by sebadrude** [comment]
perhaps I should downgrade back to 128

It's also annoying how TB makes it difficult to install older versions.

**Comment by opto** [comment]
this is a Nostalgy version that respects ctrl-something when set to Esc (use ctrl... unchecked)
and a version of textinsert where the arrow keys work

[manage_emails_nostalgy_pp_4.5.61-tb.zip](https://github.com/user-attachments/files/21567731/manage_emails_nostalgy_pp_4.5.61-tb.zip)

[text-insert1.5.13.zip](https://github.com/user-attachments/files/21567738/text-insert1.5.13.zip)

**Comment by dbergol** [comment]
Hi Opto, unfortunately the problem remains for me with unwanted focus an thus unwanted recipients with TB 140.1.0esr  and Nostalgy 4.5.61 (tested 4.5.59 as well)

Hope you can fix it completely....

Best
Daniel

**Comment by fmicolletffcam** [comment]
Oh! YEAH !!! [manage_emails_nostalgy_pp_4.5.64-tb.zip](https://github.com/user-attachments/files/21554253/manage_emails_nostalgy_pp_4.5.64-tb.zip) works just fine with TB 141.0

Thank you 1000 times Klaus!

Cursor Jumps right into the `Text` field as a few years ago (I don't remember how many).

In case it would be useful for anyone:
**TB 141.0 | Nostalgy++ 4.5.64 |Awesome 4.3 | Xorg 21.1.18
Core i5-6200U | Intel Skylake GT2 HD Graphics 520 | 8 GiB DDR3 dual channel | no swap |sata SSD**

` (141.0 (64 bits) Mozilla Thunderbird for Arch Linux)`
` $ pacman -Qs thunderbird
local/thunderbird 141.0-1`
```
$ inxi -F
System:
  Host: ArchFFCAM Kernel: 6.15.8-arch1-1 arch: x86_64 bits: 64
  Desktop: awesome v: 4.3 Distro: Arch Linux
Machine:
  Type: Laptop System: Dell product: Inspiron 5759 v: N/A
  Mobo: Dell model: 0WR8JP v: A00  UEFI: Dell v: 1.0.6 date: 09/16/2015
[...]
CPU:
  Info: dual core model: Intel Core i5-6200U bits: 64 type: MT MCP cache:
    L2: 512 KiB
  Speed (MHz): avg: 800 min/max: 400/2800 cores: 1: 800 2: 800 3: 800 4: 800
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel
[...]
  Display: x11 server: X.Org v: 21.1.18 with: Xwayland v: 24.1.8 driver: X:
    loaded: modesetting unloaded: vesa dri: iris gpu: i915 resolution:
    1: 1280x1024 60Hz 2: 1600x900 60Hz
  API: EGL v: 1.5 drivers: iris,swrast platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 25.1.6-arch1.1
    renderer: Mesa Intel HD Graphics 520 (SKL GT2)
  Info: Tools: api: eglinfo,glxinfo x11: xdriinfo, xdpyinfo, xprop, xrandr
[...]
Drives:
  Local Storage: total: 223.57 GiB used: 176.37 GiB (78.9%)
  ID-1: /dev/sda vendor: Crucial model: CT240BX500SSD1 size: 223.57 GiB
Partition:
  ID-1: / size: 219.4 GiB used: 176.28 GiB (80.3%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 496 MiB used: 88.3 MiB (17.8%) fs: vfat
    dev: /dev/sda1
Swap:
  Alert: No swap data was found.
Sensors:
  System Temperatures: cpu: 58.0 C pch: 48.5 C mobo: 41.0 C sodimm: 39.0 C
  Fan Speeds (rpm): cpu: 0
Info:
  Memory: total: 8 GiB available: 7.65 GiB used: 3.57 GiB (46.7%)
  Processes: 187 Uptime: 5h 14m Shell: Bash inxi: 3.3.38
 
$ inxi -m
Memory:
  System RAM: total: 8 GiB available: 7.65 GiB used: 3.71 GiB (48.5%)
  Array-1: capacity: 16 GiB slots: 2 modules: 2 EC: None
  Device-1: DIMM A type: DDR3 size: 4 GiB speed: 1600 MT/s
  Device-2: DIMM B type: DDR3 size: 4 GiB speed: 1600 MT/s
```

**Comment by dbergol** [comment]
YES - 4.5.64 works for me as well - thanks a lot!!!

Best
Daniel
