### ISSUE TITLE
Non-functional in TB 86.0b1?

### ISSUE THREAD

**Issue by gwhitney** [opto/nostalgy-xpi#83]
My thunderbird updated itself recently, now says it is on TB 86.0b1, and although the add-ons manager says Nostalgy is installed and enabled, nothing seems to happen. Is there perhaps an incompatibility?  Thanks for looking into this.

**Comment by opto** [comment]
yes, there are major changes in 86 for addons.
This pref may help temporarily:?  
..... You can turn e10s off/on in beta by toggling the browser.tabs.remote.autostart preference and restarting.

**Comment by gwhitney** [comment]
Ok, I toggled that preference, and nostalgy++ is operational after a restart. Thanks, happy to run with this workaround at least for a while, since I have no idea what browser.tabs.remote.autostart means/does anyway...

**Comment by opto** [comment]
86 is multiprocess, for the first time. I think that switches it back to old behaviour.

**Comment by blono** [comment]
The code is almost like a template, so I have the same problem with multiple add-ons :)
I've fixed it in the repository here for your reference!
https://github.com/protz/Manually-Sort-Folders/issues/140

**Comment by jobisoft** [comment]
Hi opto,

if you want, you can update your WL API from here:
https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis/WindowListener

There will be another change which I am still working on, and I did not want to hassle add-on devs to update multiple times, so I did not announce the update yet. But if you want beta users to be able to use nostalgy, you can of course update now already.

**Comment by opto** [comment]
thanks John,

in principle it works. The options dialog is still broken - the html inputs are horizontally next to each other, instead of top down.
Someone made an extra issue for that, so I will close this.
In general, moving with S works again.

**Comment by jobisoft** [comment]
Your best option is to replace the XUL options dialog by an html dialog. This really is the next step, ping me if you need help. Do you have tabs? The can be replaced by nice simple html+css:
https://www.w3schools.com/howto/howto_js_full_page_tabs.asp

**Comment by opto** [comment]
thanks. Yes, that is underway already. Especially, a replacement is needed/found for the truely horrible richlistbox replacement of the original listbox. 
But I personally would want a vertical separator between the tab names - I think their impementation does not truely look like tabs (consider the FF tabs without the separator...)
